language: cpp
sudo: required
dist: bionic
addons:
  apt:
    sources:
    - sourceline: 'ppa:beineri/opt-qt-5.12.3-bionic'
    packages:
    - qt512-meta-minimal
    - cmake
before_install:
  - source /opt/qt512/bin/qt512-env.sh
compiler: g++
script:
  - qmake --version
  - mkdir build
  - cd build
  - cmake .. -DRUN_TESTS=OFF
  - make
  - make test
